#!/usr/bin/env bash
#A Bash script that displays
#The content of the current directory
#In a list format
#Only display the part of the name after the first dash

index=$(ls)
for a in $index; do
  echo "$a" | cut -d '-' -f2
done
